# Generated by Django 4.0.6 on 2022-08-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('bepul', 'Bepul'), ('pullik', 'Pullik')], default='bepul', max_length=255, verbose_name='Course Status'),
        ),
        migrations.DeleteModel(
            name='CourseEnrollment',
        ),
        migrations.DeleteModel(
            name='CourseProgress',
        ),
    ]
